swagger: "2.0"
info:
  title: 'puppetdb-cli'
  version: '0.0.1'
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-Auth-Token
security:
  - APIKeyHeader: []
paths:
  /status/v1/services:
    get:
      operationId: 'getStatus'
      produces:
      - 'text/json'
      responses:
        200:
          description: 'returns trapperkeeper status of puppetdb'
          schema:
            description: 'puppetdb status'
            type: object
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      kind:
        type: string
      msg:
        type: string
      details:
        type: object
